name: Build tessellation dependencies

inputs:
  GITHUB_TOKEN:
    required: true

runs:
  using: "composite"
  steps:
    - name: Get Tessellation version to build
      shell: bash
      run: |
        version=$(grep -E 'tessellation = "' metagraph/project/Dependencies.scala | grep -o '"[^"]*"' | tr -d '"')
        echo "TESSELLATION_VERSION=v$version" >> "$GITHUB_ENV"

    - name: Clone and generate Tessellation dependencies
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
        RELEASE_TAG: ${{ env.TESSELLATION_VERSION }}
      run: |
        echo "TESSELLATION_VERSION=$RELEASE_TAG"

        mkdir -p .github/dependencies
        cd .github/dependencies
        git clone https://github.com/Constellation-Labs/tessellation.git
        cd tessellation
        git checkout "$RELEASE_TAG"

        sbt clean
        sbt sdk/publishM2