name: Deploy Testnet

on:
  push:
    branches:
      - "deploy/testnet"
jobs:
  deploy-testnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Testnet
        uses: "./.github/templates/deploy"
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_TESTNET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_TESTNET }}
          AWS_REGION: ${{ secrets.AWS_REGION_TESTNET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETWORK: testnet

          EC2_INSTANCE_1_ID: ${{ secrets.EC2_INSTANCE_1_ID_TESTNET }}
          EC2_INSTANCE_2_ID: ${{ secrets.EC2_INSTANCE_2_ID_TESTNET }}
          EC2_INSTANCE_3_ID: ${{ secrets.EC2_INSTANCE_3_ID_TESTNET }}