name: Deploy Integrationnet

on:
  push:
    branches:
      - "deploy/integrationnet"
jobs:
  deploy-integrationnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Integrationnet
        uses: "./.github/templates/deploy"
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_INTEGRATIONNET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_INTEGRATIONNET }}
          AWS_REGION: ${{ secrets.AWS_REGION_INTEGRATIONNET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETWORK: integrationnet

          EC2_INSTANCE_1_ID: ${{ secrets.EC2_INSTANCE_1_ID_INTEGRATIONNET }}
          EC2_INSTANCE_2_ID: ${{ secrets.EC2_INSTANCE_2_ID_INTEGRATIONNET }}
          EC2_INSTANCE_3_ID: ${{ secrets.EC2_INSTANCE_3_ID_INTEGRATIONNET }}