name: Deploy Mainnet

on:
  push:
    branches:
      - "deploy/mainnet"
jobs:
  deploy-mainnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Mainnet
        uses: "./.github/templates/deploy"
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_MAINNET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_MAINNET }}
          AWS_REGION: ${{ secrets.AWS_REGION_MAINNET }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETWORK: mainnet

          EC2_INSTANCE_1_ID: ${{ secrets.EC2_INSTANCE_1_ID_MAINNET }}
          EC2_INSTANCE_2_ID: ${{ secrets.EC2_INSTANCE_2_ID_MAINNET }}
          EC2_INSTANCE_3_ID: ${{ secrets.EC2_INSTANCE_3_ID_MAINNET }}