name: Deploy Integrationnet

on:
  push:
    branches:
      - "deploy/integrationnet"
jobs:
  deploy-integrationnet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy Integrationnet
        uses: "./.github/templates/deploy"
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_INTEGRATIONNET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_INTEGRATIONNET }}
          AWS_REGION: ${{ secrets.AWS_REGION_INTEGRATIONNET }}

          EC2_INSTANCE_1_ID: ${{ secrets.EC2_INSTANCE_1_ID_INTEGRATIONNET }}
          EC2_INSTANCE_2_ID: ${{ secrets.EC2_INSTANCE_2_ID_INTEGRATIONNET }}
          EC2_INSTANCE_3_ID: ${{ secrets.EC2_INSTANCE_3_ID_INTEGRATIONNET }}

      - name: Trigger Auto Restart Lambda - Integrationnet
        shell: bash
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_INTEGRATIONNET }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_INTEGRATIONNET }}
          AWS_REGION: ${{ secrets.AWS_REGION_INTEGRATIONNET }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_INTEGRATIONNET }}
        run: |
          aws lambda invoke --function-name DORMetagraphMonitor --invocation-type Event --cli-binary-format raw-in-base64-out --payload "{\"network\":\"integrationnet\",\"metagraph_id\":\"DAG5Q12Zb5UraXyGSUM3sZBkxJyyN3uRBWEvhMeU\",\"metagraph_name\":\"DOR\",\"region\":\"us-west-2\",\"base_metagraph_l0_directory\":\"/home/ubuntu/code/metagraph-l0\",\"base_currency_l1_directory\":\"/home/ubuntu/code/currency-l1\",\"base_data_l1_directory\":\"/home/ubuntu/code/data-l1\",\"cl_app_env\":\"integrationnet\",\"cl_collateral\":0,\"include_currency_l1_layer\":true,\"include_data_l1_layer\":true,\"metagraph_l0_public_port\":7000,\"metagraph_l0_p2p_port\":7001,\"metagraph_l0_cli_port\":7002,\"currency_l1_public_port\":8000,\"currency_l1_p2p_port\":8001,\"currency_l1_cli_port\":8002,\"data_l1_public_port\":9000,\"data_l1_p2p_port\":9001,\"data_l1_cli_port\":9002,\"ec2_instance_1_id\":\"${{ secrets.EC2_INSTANCE_1_ID_INTEGRATIONNET }}\",\"ec2_instance_1_ip\":\"${{ secrets.EC2_INSTANCE_1_IP_INTEGRATIONNET }}\",\"ec2_instance_2_id\":\"${{ secrets.EC2_INSTANCE_2_ID_INTEGRATIONNET }}\",\"ec2_instance_2_ip\":\"${{ secrets.EC2_INSTANCE_2_IP_INTEGRATIONNET }}\",\"ec2_instance_3_id\":\"${{ secrets.EC2_INSTANCE_3_ID_INTEGRATIONNET }}\",\"ec2_instance_3_ip\":\"${{ secrets.EC2_INSTANCE_3_IP_INTEGRATIONNET }}\",\"network_global_l0_ip\":\"3.101.147.116\",\"network_global_l0_port\":9000,\"network_global_l0_id\":\"e2f4496e5872682d7a55aa06e507a58e96b5d48a5286bfdff7ed780fa464d9e789b2760ecd840f4cb3ee6e1c1d81b2ee844c88dbebf149b1084b7313eb680714\",\"force_restart\": true}" response.json